# Generated by Django 3.2.19 on 2023-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员id')),
                ('Aname', models.CharField(max_length=20, verbose_name='管理员账号')),
                ('Apassword', models.CharField(max_length=40, verbose_name='管理员密码')),
                ('Aemail', models.CharField(max_length=20, verbose_name='管理员邮箱')),
            ],
        ),
    ]
